### ISSUE TITLE
Definir logomarca

### ISSUE THREAD

**Issue by hcalmeida-uesc** [hcalmeida-uesc/relatos-sinform-erbase#4]

**Comment by brunaatlastechnol** [comment]
Segue pasta com as logomarca criadas para a aplicação que iremos realizar. ambas estão em svg.

[LOGO.zip](https://github.com/hcalmeida-uesc/relatos-sinform-erbase/files/13262236/LOGO.zip)

**Comment by hcalmeida-uesc** [comment]
Fazer uma branch a partir da main e colocar o conteúdo dentro das pastas adequadas.
